[project]
authors = ["bitcloud2 <bitcloud22@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge", "https://conda.modular.com/max"]
description = "Easy installer for using Mochi/Magic with ComfyUI"
name = "ComfyUI"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
setup = """
    bash -c '
    set -e
    sudo apt update && \
    sudo apt install -y ffmpeg && \
    mkdir -p ./custom_nodes && \
    cd ./custom_nodes && \
    git clone https://github.com/kijai/ComfyUI-MochiWrapper && \
    git clone https://github.com/kijai/ComfyUI-KJNodes && \
    git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite && \
    cd ../models/ && \
    mkdir -p ./diffusion_models/mochi && \
    mkdir -p ./vae && \
    mkdir -p ./clip && \
    wget https://huggingface.co/Kijai/Mochi_preview_comfy/resolve/main/mochi_preview_dit_fp8_e4m3fn.safetensors -P ./diffusion_models/mochi && \
    wget https://huggingface.co/Kijai/Mochi_preview_comfy/resolve/main/mochi_preview_vae_decoder_bf16.safetensors -P ./vae && \
    wget https://huggingface.co/mcmonkey/google_t5-v1_1-xxl_encoderonly/resolve/main/t5xxl_fp8_e4m3fn.safetensors -P ./clip
    '
    """

[dependencies]
python = "==3.11"
pytorch = ">=2.5.1,<3"
cuda = "==12.4"
torchvision = ">=0.20.1,<0.21"
torchaudio = ">=2.5.1,<3"
pytorch-cuda = "12.4.*"
einops = ">=0.8.0,<0.9"
transformers = ">=4.46.1,<5"
tokenizers = ">=0.20.2,<0.21"
sentencepiece = ">=0.2.0,<0.3"
safetensors = ">=0.4.5,<0.5"
aiohttp = ">=3.10.10,<4"
pyyaml = ">=6.0.2,<7"
pillow = ">=9.4.0,<10"
scipy = ">=1.14.1,<2"
tqdm = ">=4.66.6,<5"
psutil = ">=6.1.0,<7"
accelerate = ">=1.0.1,<2"
kornia = ">=0.7.1,<0.8"
ffmpeg = { version = ">=4.4.2,<5", channel = "conda-forge" }
libjpeg-turbo = ">=2.0.0,<3"
jpeg = { version = ">=9e,<10a", channel = "conda-forge" }
setuptools = { version = ">=75.3.0,<76", channel = "conda-forge" }
websocket-client = ">=1.8.0,<2"
requests = ">=2.32.3,<3"

[pypi-dependencies]
torchsde = ">=0.2.6, <0.3"
triton = "*"
sageattention = ">=1.0.3, <2"
spandrel = ">=0.4.0, <0.5"
opencv-python = ">=4.10.0.84, <5"
